version: '2'

volumes:
  psql.data:
    driver: local
  opennms.data:
    driver: local

networks:
  opennms.net:
    driver: bridge

services:
  database:
    container_name: opennms.psql
    image: postgres:9.6.1
    env_file:
      - .postgres.env
    networks:
      - opennms.net
    volumes:
      - psql.data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  opennms:
    container_name: opennms.hzn.core.web
    image: opennms/horizon-core-web:20.0.2-1
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - opennms.net
    depends_on:
      - database
    volumes:
      - opennms.data:/opt/opennms/etc
      - opennms.data:/opennms-data
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
